apply plugin: 'com.android.library'

android {
    namespace 'com.shimmerresearch.consensysdesign'
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 34

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}

dependencies {
    // appcompat 1.7.0 is injected into every subproject by the root build.gradle
    // (afterEvaluate). This is a resources-only library, so no extra deps are needed.
}
repositories {
    mavenCentral()
}
